### ISSUE TITLE
Deploy your application to Heroku

### ISSUE THREAD

**Issue by James-Harkins** [James-Harkins/adopt_dont_shop#27]
As a visitor of the site
I will perform all user stories
By visiting the application on Heroku.
Localhost is fine for development, but
the application must be hosted on Heroku.

Use these guides: https://devcenter.heroku.com/articles/getting-started-with-rails5

**Comment by CLRM1** [comment]
We're both set up to deploy to the same Heroku app now. [Heroko URL](https://blooming-ridge-74197.herokuapp.com/)
